### ISSUE TITLE
Would it be possible/easy to run SSR on dev mode?

### ISSUE THREAD

**Issue by ericaprieto** [reactivestack/parcel-react-ssr#2]
Would it be possible/easy to run SSR on dev mode?

**Comment by eXon** [comment]
You cannot do SSR on dev mode unfortunally. You have to restart node.js so it knows the file has been changed. You can however disable minification for debugging purposes in production if this is what you need.

**Comment by krazyjakee** [comment]
Would a comfortable work-around be to use something like nodemon to retrigger a rebuild with "NODE_ENV" set to development? I have been using this method when working on the server to force rebuild when changes occur. It does not restart the browser, but at least it saves some time.
