### ISSUE TITLE
Asset paths aren't being transpiled on SSR

### ISSUE THREAD

**Issue by ericaprieto** [reactivestack/parcel-react-ssr#3]
Things like `import logo from './react/png'` throws `Error: Cannot find module './react.png'` on SSR

**Comment by gmchaturvedi1** [comment]
+1 i am facing the same issue,Can u help us on this .

**Comment by eXon** [comment]
I am currently waiting on my PR https://github.com/parcel-bundler/parcel/pull/453 to get merged. I think it would be easier to bundle a server version using Parcel so we don't need to setup a bunch of stuff. Right now, the raw assets (like images).

It looks like we would need a babel plugin transforming your filename with the correct MD5 hash name. See https://github.com/parcel-bundler/parcel/blob/master/src/Asset.js#L170 for how the file name is generated.

I would rather wait for my PR to get merged and bundle something for the server without any work.

**Comment by dasblitz** [comment]
I ran into this to along with .scss files not working. I ended up adding a build step that copied `src/assets` to `dist/client/assets` along with making a few changes to my .babelrc to skip .scss imports in babel, and fixing the import paths for assets.

my .babelrc looks like this:
```
{
  "presets": ["env", "react"],
  "env": {
    "node": {
      "plugins": [
        [
          "babel-plugin-transform-require-ignore",
          {
            "extensions": [".css", ".scss"]
          }
        ],
        [
          "transform-assets-import-to-string",
          {
            "baseDir": "/assets",
            "baseUri": ""
          }
        ]
      ]
    }
  }
}
```

_(so you need to run `npm -i babel-plugin-transform-assets-import-to-string --save-dev`)_

and the scripts section in my package.json looks like this:
```
"scripts": {
    "start": "parcel src/index.html",
    "build": "rimraf dist && npm run build-client && npm run build-server && npm run copy-assets",
    "build-client": "parcel build src/index.html -d dist/client --public-url /dist",
    "build-server": "cross-env BABEL_ENV=node babel src -d dist/server --ignore __tests__",
    "copy-assets": "cp -R src/assets dist/client/assets",
    "test": "jest"
  },
```
_(notice the extra `copy-assets` task. Also I'm on a mac so `cp -R src/assets dist/client/assets` might not work for other OS'es)_

now I'm able to do imports like this in `src/components/App.jsx`:
`import '../assets/scss/main.scss'`
`import myImage from '../assets/img/case-logo-ers.png'`

And I can use `myImage` like this:
`<img src={'/dist' + myImage} />`

**Comment by eXon** [comment]
This should be fixed now. With the last version, I'm bundling a Node.js version and the image file should be there now.
