### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by krazyjakee** [reactivestack/parcel-react-ssr#4]
How would I implement code splitting in this solution?

I have a large multi-page application and some of the Routes have specific dependencies. I don't want to load them all for every page a user might visit. How can I only load them for that route?

I absolutely love what you're trying to do here, it's very exciting. Please keep up the good fight and I will try to help where I can.

**Comment by eXon** [comment]
HI @krazyjakee 

Code splitting is pretty easy to do with Parcel. You can read more there: https://parceljs.org/code_splitting.html

Have you tried it?

You should also look at the last version of this repo. Now the Node.js version is also managed by Parcel so it's even less stuff to setup :)

**Comment by krazyjakee** [comment]
I presumed there was something special about react with routes etc. I'll have a play around and see what can be done.
