### ISSUE TITLE
Simplify?

### ISSUE THREAD

**Issue by krazyjakee** [reactivestack/parcel-react-ssr#5]
I love this.

I see this as some kind of boilerplate for other developers to get going with their Parcel SSR projects. Is that the case? If so, I wonder if we might simplify the project a little more. The Apollo client is so deeply coded into the core functionality and I think we can achieve a better demo by just having a couple simple pages with hello world. After all, we're not demoing apollo client or an authentication system, we just need to show SSR in action, perhaps with a couple of hello world pages. Can the polyfill also be removed?

I just want your opinion before filing a destructive pull request.

**Comment by kudos** [comment]
As someone struggling to get the demo to work correctly due to errors from the Apollo client, I agree with this.

**Comment by andymeek** [comment]
Hi guys, I saw this really cool repo but need to simplify it myself for another project - so decided to remove Apollo, upgrade the packages, and add SCSS.

I've just seen these comments and have forked, made the changes and pushed to - https://github.com/andymeek/parcel-react-ssr

I hope you find it useful.

**Comment by andymeek** [comment]
@eXon Great!

**Comment by eXon** [comment]
Hey @krazyjakee @kudos @andymeek

I've done a rewrite that only use Parcel, even for the server-side so it's even less stuff to setup! I've also got rid of the apollo stuff and kept it as a simple hello world with react-router and react-helmet.

Let me know what you think! 

Also if you spot some grammar mistakes, English is not my first language so let me know :)

**Comment by krazyjakee** [comment]
I'm super happy with this. Shall we see what other things would be nice? I'll start a new issue.
